# Generated by Django 6.0.7 on 2026-07-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image_path_alter_productmedia_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeguiderow',
            name='bottom_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Bottom/Trouser Length'),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='chest',
            field=models.FloatField(blank=True, null=True, verbose_name='Bust'),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Full Length'),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='size_code',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='sleeve_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Sleeve Length'),
        ),
    ]
