# Generated by Django 6.0.7 on 2026-07-29 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_sizeguiderow_bottom_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeguiderow',
            name='bottom_length',
        ),
        migrations.AlterField(
            model_name='product',
            name='bottom_type',
            field=models.CharField(blank=True, choices=[('Shalwar', 'Shalwar'), ('Trouser', 'Trouser'), ('Skirt', 'Skirt')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BottomSizeGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='in', max_length=5)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bottom_size_guide', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='BottomSizeGuideRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_code', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('hips', models.FloatField(blank=True, null=True, verbose_name='Hip')),
                ('length', models.FloatField(blank=True, null=True)),
                ('bottom_size_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='store.bottomsizeguide')),
            ],
        ),
    ]
