# Generated by Django 6.0.7 on 2026-07-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sizeguiderow_bottom_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottomsizeguiderow',
            name='bottom_size_guide',
        ),
        migrations.RemoveField(
            model_name='sizeguiderow',
            name='hips',
        ),
        migrations.AddField(
            model_name='sizeguiderow',
            name='bottom_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Trouser Length'),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='chest',
            field=models.FloatField(blank=True, null=True, verbose_name='Chest'),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Dress Length'),
        ),
        migrations.AlterField(
            model_name='sizeguiderow',
            name='waist',
            field=models.FloatField(blank=True, null=True, verbose_name='Waist'),
        ),
        migrations.DeleteModel(
            name='BottomSizeGuide',
        ),
        migrations.DeleteModel(
            name='BottomSizeGuideRow',
        ),
    ]
